language: cpp
before_script:
- sudo apt-get install python-pip -y
- sudo pip install conan
- conan profile update settings.compiler.libcxx=libstdc++11
script:
- mkdir conan_files && cd conan_files
- conan install ..
- ls
- cd ..

- cmake .
- cmake --build .
- ctest .
- cmake --build . --target package
deploy:
  provider: bintray
  file: description.json
  user: $BINTRAY_USER
  key: $BINTRAY_API_KEY
  skip_cleanup: true
